- hosts: dbservers
  sudo: yes

  tasks:
    - name: ensure apt-cache is up to date
      action: apt update_cache=yes

    - name: ensure packages are installed
      action: apt name={{item}}
      with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

- hosts: dbservers
  sudo: yes
  sudo_user: postgres

  vars:
    dbname: drop-server
    dbuser: drop-server
    dbpassword: billyisadopted

  tasks:
    - name: ensure database is created
      postgresql_db: name={{dbname}}

    - name: ensure user has access to database
      postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

    - name: ensure user does not have unnecessary privilege
      postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
