- hosts: webservers
  sudo: yes
  gather_facts: no

  tasks:
    - name: ensure packages are installed
      action: apt name={{item}}
      with_items:
        - nginx
        - libmcrypt-dev
        - git
        - python-pip

    - name: ensure folders exists
      file: dest={{item}} state=directory
      with_items:
        - /srv/snapchat_saves
        - /var/log/drop-server

    - name: fetch the server
      git: repo=https://github.com/nickhs/drop-server.git dest=/srv/drop-server accept_hostkey=true

    - name: install requirements
      pip: requirements=/srv/drop-server/requirements.txt
